
version: '3.8'
services:
  kubernetesapp-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/kubernetesapp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kubernetesapp
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
