---
apiVersion: v1
kind: Service
metadata:
    name: kubrenetesapp
    labels:
        app: kubrenetesapp
spec:
    type: NodePort
    selector:
        app: kubrenetesapp
    ports:
        - protocol: TCP
          port: 8020
          name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kubrenetesapp
spec:
    selector:
        matchLabels:
            app: kubrenetesapp
    replicas: 3
    template:
        metadata:
            labels:
                app: kubrenetesapp
        spec:
            containers:
                - name: kubrenetesapp
                  image: medboutaieb/kubrenetesapp:latest
                  ports:
                      - containerPort: 8020
                  livenessProbe:
                      httpGet:
                          path: /healthcheck
                          port: 8025
                      initialDelaySeconds: 30
                      timeoutSeconds: 1
